#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ParentPortal.Droid.Resource", IsApplication=true)]

namespace ParentPortal.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F02000A
			public const int announcements_icon = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int background_splash = 2130837515;
			
			// aapt resource value: 0x7F020000
			public const int Bookmarked_icon = 2130837504;
			
			// aapt resource value: 0x7F02000C
			public const int bookmark_icon = 2130837516;
			
			// aapt resource value: 0x7F020001
			public const int Bottle_icon = 2130837505;
			
			// aapt resource value: 0x7F02000D
			public const int calendar = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int circular_cross = 2130837518;
			
			// aapt resource value: 0x7F020002
			public const int Commented_icon = 2130837506;
			
			// aapt resource value: 0x7F02000F
			public const int cross_black_icon = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int cross_icon = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int down_arrow = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int education = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int emoji_icon = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int error_warning_icon = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int events_Icon = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int facebook = 2130837526;
			
			// aapt resource value: 0x7F020003
			public const int Filter_icon = 2130837507;
			
			// aapt resource value: 0x7F020017
			public const int food_Icon = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int group_splash = 2130837528;
			
			// aapt resource value: 0x7F020004
			public const int HamburgerNav = 2130837508;
			
			// aapt resource value: 0x7F020019
			public const int health = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int help_and_feedback = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int home = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int instagram = 2130837532;
			
			// aapt resource value: 0x7F020005
			public const int Liked_icon = 2130837509;
			
			// aapt resource value: 0x7F02001D
			public const int login_background = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int logo_splash = 2130837534;
			
			// aapt resource value: 0x7F020006
			public const int Meal_icon = 2130837510;
			
			// aapt resource value: 0x7F02001F
			public const int messages = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int morning_tea_icon = 2130837536;
			
			// aapt resource value: 0x7F020007
			public const int Notifications = 2130837511;
			
			// aapt resource value: 0x7F020021
			public const int parent_request = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int pencil_edit = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int photos_Icon = 2130837539;
			
			// aapt resource value: 0x7F020008
			public const int Photos_side_Icon = 2130837512;
			
			// aapt resource value: 0x7F020024
			public const int remote_learning_icon = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int right_arrow_icon = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int right_icon = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int search = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int select_date = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int settings_icon = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int sign_out_icon = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int sleep_Icon = 2130837547;
			
			// aapt resource value: 0x7F020009
			public const int Spinner = 2130837513;
			
			// aapt resource value: 0x7F02002C
			public const int splash_background = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int splash_launch = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int splash_logo = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int splash_logotext = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int splash_screen = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int splash_text = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int staff_icon = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int sun_icon = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int text_splash = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int text_splashlogo = 2130837557;
			
			// aapt resource value: 0x7F020038
			public const int tga_banner = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int tga_comments_icon = 2130837561;
			
			// aapt resource value: 0x7F020036
			public const int tga_Fruits = 2130837558;
			
			// aapt resource value: 0x7F02003A
			public const int tga_like = 2130837562;
			
			// aapt resource value: 0x7F020037
			public const int tga_Water = 2130837559;
			
			// aapt resource value: 0x7F02003B
			public const int user_f = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int user_s = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int youtube = 2130837565;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int AppCompatDialogStyle = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int MainTheme = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MainTheme_Base = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int MyTheme = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int MyTheme_Base = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int MyTheme_Splash = 2130968581;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
